services:
  traefik:
    image: traefik:v3.1
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.grpc.address=:9082
    ports: ['80:80', '8080:8080', '9082:9082']
    volumes: ['/var/run/docker.sock:/var/run/docker.sock:ro']
    networks: [web]
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports: ['5432:5432']
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      traefik:
        condition: service_started
    healthcheck:
      test: [CMD, pg_isready, -U, postgres]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    networks: [web]
  pg-admin:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: ['5430:80']
    labels:
      - traefik.enable=true
      - traefik.http.routers.pg-admin.rule=Host(`pg-admin.localhost`)
      - traefik.http.routers.pg-admin.entrypoints=web
      - traefik.http.services.pg-admin.loadbalancer.server.port=80
    depends_on:
      db:
        condition: service_healthy
      traefik:
        condition: service_started
    networks: [web]
  grpc-server:
    build:
      context: ./grpc
      dockerfile: Dockerfile
    environment:
      - GRPCADDR=:9082
      - DSN=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
    ports: ['9082']
    labels:
      - traefik.enable=true
      - traefik.http.routers.grpc-server.rule=Host(`grpc-server.localhost`)
      - traefik.http.routers.grpc-server.loadbalancer.server.scheme=h2c
      - traefik.http.services.grpc-server.loadbalancer.server.port=9082
    healthcheck:
      test: ["CMD", "/bin/sh", "-c", "bin/grpc_health_probe -addr=:9082 2>&1 | grep -q -E 'SERVING|NOT_SERVING'"]
      interval: 30s
      timeout: 30s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
      traefik:
        condition: service_started
    networks: [web]
  shipping-service:
    build:
      context: ./shipping
      dockerfile: Dockerfile
    environment:
      - DB_DSN=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
      - SERVER_ADDR=:9091
      - K_SERVERS=localhost:9094
      - K_OFFSET=latest
      - K_CONSUMER_GROUP=amit
      - K_ACKS=all
    ports: ['9091:9091']
    labels:
      - traefik.enable=true
      - traefik.http.routers.shipping-service.rule=Host(`shipping-service.localhost`)
      - traefik.http.routers.shipping-service.entrypoints=web
      - traefik.http.services.shipping-service.loadbalancer.server.port=9091
    depends_on:
      db:
        condition: service_healthy
      traefik:
        condition: service_started
    networks: [web]
  order-service:
    build:
      context: ./order
      dockerfile: Dockerfile
    environment:
      - SERVERADDR=:9090
      - GRPCADDR=grpc-server:9082
      - K_SERVERS=localhost:9094
      - K_OFFSET=latest
      - K_CONSUMER_GROUP=amit
      - K_ACKS=all
    ports: ['9090:9090']
    labels:
      - traefik.enable=true
      - traefik.http.routers.order-service.rule=Host(`order-service.localhost`)
      - traefik.http.routers.order-service.entrypoints=web
      - traefik.http.services.order-service.loadbalancer.server.port=9090
    depends_on:
      db:
        condition: service_healthy
      traefik:
        condition: service_started
    networks: [web]
networks:
  web:
    external: true
